version: "3"
services:
  master:
    container_name: master
    image: jenkins:2.60.3-alpine
    ports: 
      - "9090:8080" # 8080 값은 docker hub image doc 참고
    volumes:
      - ./jenkins_home:/var/jenkins_home # 해당 이미지 JENKINS_HOME 환경변수 값 사용
    